In [62]:
import pandas as pd

In [82]:
df_og = pd.read_csv("ShowcaseDataWinter2023.csv")
df_og

,price,appraisal_offer,online_appraisal_flag,model_year,mileage,make,model,trim_descrip,body,color,...,trim_descrip_appraisal,body_appraisal,color_appraisal,engine_appraisal,cylinders_appraisal,mpg_city_appraisal,mpg_highway_appraisal,horsepower_appraisal,fuel_capacity_appraisal,market
0,$20k to $25k,$0k to $5k,1.0,2014.0,15k to 20k miles,HDT,HDT_12,Premium,E,Red,...,NaN,D,Silver,4.0L,6,17.0,21,236,21.0,13
1,$15k to $20k,$0k to $5k,0.0,2006.0,100k+ miles,KQZ,KQZ_23,Premium,E,Silver,...,Not Premium,D,Gold,4.2L,6,16.0,21,205,25.0,11
2,$30k to $35k,$35k to $40k,1.0,2014.0,5k to 10k miles,CZV,CZV_10,Premium,E,Black,...,NaN,E,Red,2.0L,4,41.0,38,181,10.0,13
3,$35k to $40k,$5k to $10k,1.0,2014.0,15k to 20k miles,IZA,IZA_19,Premium,F,Silver,...,Premium,F,Blue,3.0L,6,17.0,25,230,16.0,13
4,$30k to $35k,$15k to $20k,1.0,2011.0,35k to 40k miles,HDT,HDT_8,Premium,F,Blue,...,Not Premium,E,Black,2.4L,4,20.0,29,182,18.0,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,$15k to $20k,$15k to $20k,1.0,2013.0,10k to 15k miles,OFW,OFW_6,Premium,F,Black,...,Not Premium,E,Black,1.4L,4,26.0,31,138,14.0,1
199996,$20k to $25k,$10k to $15k,0.0,2014.0,55k to 60k miles,ARU,ARU_12,Not Premium,F,White,...,Not Premium,B,Black,1.8L,4,30.0,39,143,13.0,8
199997,$30k to $35k,$0k to $5k,0.0,2014.0,10k to 15k miles,AIH,AIH_13,Premium,F,Silver,...,Not Premium,F,Gray,2.4L,4,21.0,30,177,18.0,3
199998,$30k to $35k,$10k to $15k,0.0,2012.0,50k to 55k miles,KQZ,KQZ_3,Not Premium,D,Black,...,Premium,D,White,5.7L,8,13.0,19,390,26.0,11
199999,$50k to $55k,$15k to $20k,0.0,2014.0,5k to 10k miles,CIP,CIP_22,Premium,E,Black,...,Premium,E,Blue,5.7L,8,18.0,25,360,24.0,14

In [65]:
df_samp = pd.read_csv("ShowcaseSample.csv")
df_samp

,price,appraisal_offer,online_appraisal_flag,model_year,mileage,make,model,trim_descrip,body,color,...,trim_descrip_appraisal,body_appraisal,color_appraisal,engine_appraisal,cylinders_appraisal,mpg_city_appraisal,mpg_highway_appraisal,horsepower_appraisal,fuel_capacity_appraisal,market
0,$20k to $25k,$0k to $5k,1,2014.0,15k to 20k miles,HDT,HDT_12,Premium,E,Red,...,NaN,D,Silver,4.0L,6,17,21,236,21,13
1,$15k to $20k,$0k to $5k,0,2006.0,100k+ miles,KQZ,KQZ_23,Premium,E,Silver,...,Not Premium,D,Gold,4.2L,6,16,21,205,25,11
2,$30k to $35k,$35k to $40k,1,2014.0,5k to 10k miles,CZV,CZV_10,Premium,E,Black,...,NaN,E,Red,2.0L,4,41,38,181,10,13
3,$35k to $40k,$5k to $10k,1,2014.0,15k to 20k miles,IZA,IZA_19,Premium,F,Silver,...,Premium,F,Blue,3.0L,6,17,25,230,16,13
4,$30k to $35k,$15k to $20k,1,2011.0,35k to 40k miles,HDT,HDT_8,Premium,F,Blue,...,Not Premium,E,Black,2.4L,4,20,29,182,18,16
5,$15k to $20k,$5k to $10k,0,2013.0,35k to 40k miles,OFW,OFW_11,Not Premium,F,White,...,Not Premium,F,Black,3.6L,6,18,27,292,19,10
6,$35k to $40k,$40k+,0,2013.0,20k to 25k miles,LTX,LTX_21,Premium,B,Blue,...,Not Premium,B,Black,6.2L,8,16,25,455,18,8
7,$15k to $20k,$5k to $10k,0,2012.0,30k to 35k miles,LTX,LTX_30,Not Premium,E,Black,...,Not Premium,F,Silver,1.8L,4,30,39,143,13,1
8,$30k to $35k,$20k to $25k,0,2013.0,35k to 40k miles,FVQ,FVQ_4,Premium,E,Black,...,Premium,E,Black,3.6L,6,17,24,288,22,9
9,$20k to $25k,$0k to $5k,0,2015.0,45k to 50k miles,ARU,ARU_4,Not Premium,E,Gray,...,Not Premium,E,Blue,4.7L,8,15,21,235,20,16
10,$30k to $35k,$5k to $10k,1,2014.0,15k to 20k miles,HXQ,HXQ_14,Premium,F,Blue,...,NaN,F,Silver,3.5L,6,21,30,272,18,11
11,$45k to $50k,$0k to $5k,0,2012.0,70k to 75k miles,BDP,BDP_11,NaN,E,Burgundy,...,NaN,E,Burgundy,3.5L,6,16,21,268,21,12

In [64]:
import re

In [98]:

data = []
for i in range(len(df_samp)):
    local = df_samp.iloc[i]['price'].replace('$', '').replace('k', '')
    gen = [int(s) for s in local.split() if s.isdigit()]
    numbers = [i * 1000 for i in gen]
    average = sum(numbers) / len(numbers)
    d = {'price_list': numbers, 'price_average' : average}
    data.append(d)
df_samp_add = pd.DataFrame(data)
df_samp_final = df_samp.join(df_samp_add)
second_col = df_samp_final.pop('price_list')
df_samp_final.insert(1, 'price_list', second_col)
third_col = df_samp_final.pop('price_average')
df_samp_final.insert(2, 'price_average', third_col)
df_samp_final
df_samp2 = df_samp_final
df_samp2

,price,price_list,price_average,appraisal_offer,online_appraisal_flag,model_year,mileage,make,model,trim_descrip,...,trim_descrip_appraisal,body_appraisal,color_appraisal,engine_appraisal,cylinders_appraisal,mpg_city_appraisal,mpg_highway_appraisal,horsepower_appraisal,fuel_capacity_appraisal,market
0,$20k to $25k,"[20000, 25000]",22500.0,$0k to $5k,1,2014.0,15k to 20k miles,HDT,HDT_12,Premium,...,NaN,D,Silver,4.0L,6,17,21,236,21,13
1,$15k to $20k,"[15000, 20000]",17500.0,$0k to $5k,0,2006.0,100k+ miles,KQZ,KQZ_23,Premium,...,Not Premium,D,Gold,4.2L,6,16,21,205,25,11
2,$30k to $35k,"[30000, 35000]",32500.0,$35k to $40k,1,2014.0,5k to 10k miles,CZV,CZV_10,Premium,...,NaN,E,Red,2.0L,4,41,38,181,10,13
3,$35k to $40k,"[35000, 40000]",37500.0,$5k to $10k,1,2014.0,15k to 20k miles,IZA,IZA_19,Premium,...,Premium,F,Blue,3.0L,6,17,25,230,16,13
4,$30k to $35k,"[30000, 35000]",32500.0,$15k to $20k,1,2011.0,35k to 40k miles,HDT,HDT_8,Premium,...,Not Premium,E,Black,2.4L,4,20,29,182,18,16
5,$15k to $20k,"[15000, 20000]",17500.0,$5k to $10k,0,2013.0,35k to 40k miles,OFW,OFW_11,Not Premium,...,Not Premium,F,Black,3.6L,6,18,27,292,19,10
6,$35k to $40k,"[35000, 40000]",37500.0,$40k+,0,2013.0,20k to 25k miles,LTX,LTX_21,Premium,...,Not Premium,B,Black,6.2L,8,16,25,455,18,8
7,$15k to $20k,"[15000, 20000]",17500.0,$5k to $10k,0,2012.0,30k to 35k miles,LTX,LTX_30,Not Premium,...,Not Premium,F,Silver,1.8L,4,30,39,143,13,1
8,$30k to $35k,"[30000, 35000]",32500.0,$20k to $25k,0,2013.0,35k to 40k miles,FVQ,FVQ_4,Premium,...,Premium,E,Black,3.6L,6,17,24,288,22,9
9,$20k to $25k,"[20000, 25000]",22500.0,$0k to $5k,0,2015.0,45k to 50k miles,ARU,ARU_4,Not Premium,...,Not Premium,E,Blue,4.7L,8,15,21,235,20,16
10,$30k to $35k,"[30000, 35000]",32500.0,$5k to $10k,1,2014.0,15k to 20k miles,HXQ,HXQ_14,Premium,...,NaN,F,Silver,3.5L,6,21,30,272,18,11
11,$45k to $50k,"[45000, 50000]",47500.0,$0k to $5k,0,2012.0,70k to 75k miles,BDP,BDP_11,NaN,...,NaN,E,Burgundy,3.5L,6,16,21,268,21,12

In [83]:
data = []
for i in range(len(df_og)):
    local = df_og.iloc[i]['price'].replace('$', '').replace('k', '').replace('+', ' ')
    gen = [int(s) for s in local.split() if s.isdigit()]
    numbers = [i * 1000 for i in gen]
    average = sum(numbers) / len(numbers)
    d = {'price_list': numbers, 'price_average' : average}
    data.append(d)
df_add = pd.DataFrame(data)
df_full = df_og.join(df_add)
second_col = df_full.pop('price_list')
df_full.insert(1, 'price_list', second_col)
third_col = df_full.pop('price_average')
df_full.insert(2, 'price_average', third_col)
df_full

,price,price_list,price_average,appraisal_offer,online_appraisal_flag,model_year,mileage,make,model,trim_descrip,...,trim_descrip_appraisal,body_appraisal,color_appraisal,engine_appraisal,cylinders_appraisal,mpg_city_appraisal,mpg_highway_appraisal,horsepower_appraisal,fuel_capacity_appraisal,market
0,$20k to $25k,"[20000, 25000]",22500.0,$0k to $5k,1.0,2014.0,15k to 20k miles,HDT,HDT_12,Premium,...,NaN,D,Silver,4.0L,6,17.0,21,236,21.0,13
1,$15k to $20k,"[15000, 20000]",17500.0,$0k to $5k,0.0,2006.0,100k+ miles,KQZ,KQZ_23,Premium,...,Not Premium,D,Gold,4.2L,6,16.0,21,205,25.0,11
2,$30k to $35k,"[30000, 35000]",32500.0,$35k to $40k,1.0,2014.0,5k to 10k miles,CZV,CZV_10,Premium,...,NaN,E,Red,2.0L,4,41.0,38,181,10.0,13
3,$35k to $40k,"[35000, 40000]",37500.0,$5k to $10k,1.0,2014.0,15k to 20k miles,IZA,IZA_19,Premium,...,Premium,F,Blue,3.0L,6,17.0,25,230,16.0,13
4,$30k to $35k,"[30000, 35000]",32500.0,$15k to $20k,1.0,2011.0,35k to 40k miles,HDT,HDT_8,Premium,...,Not Premium,E,Black,2.4L,4,20.0,29,182,18.0,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,$15k to $20k,"[15000, 20000]",17500.0,$15k to $20k,1.0,2013.0,10k to 15k miles,OFW,OFW_6,Premium,...,Not Premium,E,Black,1.4L,4,26.0,31,138,14.0,1
199996,$20k to $25k,"[20000, 25000]",22500.0,$10k to $15k,0.0,2014.0,55k to 60k miles,ARU,ARU_12,Not Premium,...,Not Premium,B,Black,1.8L,4,30.0,39,143,13.0,8
199997,$30k to $35k,"[30000, 35000]",32500.0,$0k to $5k,0.0,2014.0,10k to 15k miles,AIH,AIH_13,Premium,...,Not Premium,F,Gray,2.4L,4,21.0,30,177,18.0,3
199998,$30k to $35k,"[30000, 35000]",32500.0,$10k to $15k,0.0,2012.0,50k to 55k miles,KQZ,KQZ_3,Not Premium,...,Premium,D,White,5.7L,8,13.0,19,390,26.0,11
199999,$50k to $55k,"[50000, 55000]",52500.0,$15k to $20k,0.0,2014.0,5k to 10k miles,CIP,CIP_22,Premium,...,Premium,E,Blue,5.7L,8,18.0,25,360,24.0,14

In [100]:
df_og2 = df_full
df_og2

,price,price_list,price_average,appraisal_offer,online_appraisal_flag,model_year,mileage,make,model,trim_descrip,...,trim_descrip_appraisal,body_appraisal,color_appraisal,engine_appraisal,cylinders_appraisal,mpg_city_appraisal,mpg_highway_appraisal,horsepower_appraisal,fuel_capacity_appraisal,market
0,$20k to $25k,"[20000, 25000]",22500.0,$0k to $5k,1.0,2014.0,15k to 20k miles,HDT,HDT_12,Premium,...,NaN,D,Silver,4.0L,6,17.0,21,236,21.0,13
1,$15k to $20k,"[15000, 20000]",17500.0,$0k to $5k,0.0,2006.0,100k+ miles,KQZ,KQZ_23,Premium,...,Not Premium,D,Gold,4.2L,6,16.0,21,205,25.0,11
2,$30k to $35k,"[30000, 35000]",32500.0,$35k to $40k,1.0,2014.0,5k to 10k miles,CZV,CZV_10,Premium,...,NaN,E,Red,2.0L,4,41.0,38,181,10.0,13
3,$35k to $40k,"[35000, 40000]",37500.0,$5k to $10k,1.0,2014.0,15k to 20k miles,IZA,IZA_19,Premium,...,Premium,F,Blue,3.0L,6,17.0,25,230,16.0,13
4,$30k to $35k,"[30000, 35000]",32500.0,$15k to $20k,1.0,2011.0,35k to 40k miles,HDT,HDT_8,Premium,...,Not Premium,E,Black,2.4L,4,20.0,29,182,18.0,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,$15k to $20k,"[15000, 20000]",17500.0,$15k to $20k,1.0,2013.0,10k to 15k miles,OFW,OFW_6,Premium,...,Not Premium,E,Black,1.4L,4,26.0,31,138,14.0,1
199996,$20k to $25k,"[20000, 25000]",22500.0,$10k to $15k,0.0,2014.0,55k to 60k miles,ARU,ARU_12,Not Premium,...,Not Premium,B,Black,1.8L,4,30.0,39,143,13.0,8
199997,$30k to $35k,"[30000, 35000]",32500.0,$0k to $5k,0.0,2014.0,10k to 15k miles,AIH,AIH_13,Premium,...,Not Premium,F,Gray,2.4L,4,21.0,30,177,18.0,3
199998,$30k to $35k,"[30000, 35000]",32500.0,$10k to $15k,0.0,2012.0,50k to 55k miles,KQZ,KQZ_3,Not Premium,...,Premium,D,White,5.7L,8,13.0,19,390,26.0,11
199999,$50k to $55k,"[50000, 55000]",52500.0,$15k to $20k,0.0,2014.0,5k to 10k miles,CIP,CIP_22,Premium,...,Premium,E,Blue,5.7L,8,18.0,25,360,24.0,14

In [101]:
data = []
for i in range(len(df_og2)):
    local = df_og2.iloc[i]['appraisal_offer'].replace('$', '').replace('k', '').replace('+', ' ')
    gen = [int(s) for s in local.split() if s.isdigit()]
    numbers = [i * 1000 for i in gen]
    average = sum(numbers) / len(numbers)
    d = {'appraisal_offer_list': numbers, 'appraisal_offer_average' : average}
    data.append(d)
df_add2 = pd.DataFrame(data)
df_full2 = df_og2.join(df_add2)
second_col = df_full2.pop('appraisal_offer_list')
df_full2.insert(4, 'appraisal_offer_list', second_col)
third_col = df_full2.pop('appraisal_offer_average')
df_full2.insert(5, 'appraisal_offer_average', third_col)
df_full2

,price,price_list,price_average,appraisal_offer,appraisal_offer_list,appraisal_offer_average,online_appraisal_flag,model_year,mileage,make,...,trim_descrip_appraisal,body_appraisal,color_appraisal,engine_appraisal,cylinders_appraisal,mpg_city_appraisal,mpg_highway_appraisal,horsepower_appraisal,fuel_capacity_appraisal,market
0,$20k to $25k,"[20000, 25000]",22500.0,$0k to $5k,"[0, 5000]",2500.0,1.0,2014.0,15k to 20k miles,HDT,...,NaN,D,Silver,4.0L,6,17.0,21,236,21.0,13
1,$15k to $20k,"[15000, 20000]",17500.0,$0k to $5k,"[0, 5000]",2500.0,0.0,2006.0,100k+ miles,KQZ,...,Not Premium,D,Gold,4.2L,6,16.0,21,205,25.0,11
2,$30k to $35k,"[30000, 35000]",32500.0,$35k to $40k,"[35000, 40000]",37500.0,1.0,2014.0,5k to 10k miles,CZV,...,NaN,E,Red,2.0L,4,41.0,38,181,10.0,13
3,$35k to $40k,"[35000, 40000]",37500.0,$5k to $10k,"[5000, 10000]",7500.0,1.0,2014.0,15k to 20k miles,IZA,...,Premium,F,Blue,3.0L,6,17.0,25,230,16.0,13
4,$30k to $35k,"[30000, 35000]",32500.0,$15k to $20k,"[15000, 20000]",17500.0,1.0,2011.0,35k to 40k miles,HDT,...,Not Premium,E,Black,2.4L,4,20.0,29,182,18.0,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,$15k to $20k,"[15000, 20000]",17500.0,$15k to $20k,"[15000, 20000]",17500.0,1.0,2013.0,10k to 15k miles,OFW,...,Not Premium,E,Black,1.4L,4,26.0,31,138,14.0,1
199996,$20k to $25k,"[20000, 25000]",22500.0,$10k to $15k,"[10000, 15000]",12500.0,0.0,2014.0,55k to 60k miles,ARU,...,Not Premium,B,Black,1.8L,4,30.0,39,143,13.0,8
199997,$30k to $35k,"[30000, 35000]",32500.0,$0k to $5k,"[0, 5000]",2500.0,0.0,2014.0,10k to 15k miles,AIH,...,Not Premium,F,Gray,2.4L,4,21.0,30,177,18.0,3
199998,$30k to $35k,"[30000, 35000]",32500.0,$10k to $15k,"[10000, 15000]",12500.0,0.0,2012.0,50k to 55k miles,KQZ,...,Premium,D,White,5.7L,8,13.0,19,390,26.0,11
199999,$50k to $55k,"[50000, 55000]",52500.0,$15k to $20k,"[15000, 20000]",17500.0,0.0,2014.0,5k to 10k miles,CIP,...,Premium,E,Blue,5.7L,8,18.0,25,360,24.0,14

In [102]:
df_og3 = df_full2

In [110]:
data = []
for i in range(len(df_og3)):
    local = df_og3.iloc[i]['mileage'].replace('$', '').replace('k', '').replace('+', ' ')
    gen = [int(s) for s in local.split() if s.isdigit()]
    numbers = [i * 1000 for i in gen]
    average = sum(numbers) / len(numbers)
    d = {'mileage_list': numbers, 'mileage_average' : average}
    data.append(d)
df_add3 = pd.DataFrame(data)
df_full3 = df_og3.join(df_add3)
second_col = df_full3.pop('mileage_list')
df_full3.insert(9, 'mileage_list', second_col)
third_col = df_full3.pop('mileage_average')
df_full3.insert(10, 'mileage_average', third_col)

,price,price_list,price_average,appraisal_offer,appraisal_offer_list,appraisal_offer_average,online_appraisal_flag,model_year,mileage,mileage_list,...,trim_descrip_appraisal,body_appraisal,color_appraisal,engine_appraisal,cylinders_appraisal,mpg_city_appraisal,mpg_highway_appraisal,horsepower_appraisal,fuel_capacity_appraisal,market
0,$20k to $25k,"[20000, 25000]",22500.0,$0k to $5k,"[0, 5000]",2500.0,1.0,2014.0,15k to 20k miles,"[15000, 20000]",...,NaN,D,Silver,4.0L,6,17.0,21,236,21.0,13
1,$15k to $20k,"[15000, 20000]",17500.0,$0k to $5k,"[0, 5000]",2500.0,0.0,2006.0,100k+ miles,[100000],...,Not Premium,D,Gold,4.2L,6,16.0,21,205,25.0,11
2,$30k to $35k,"[30000, 35000]",32500.0,$35k to $40k,"[35000, 40000]",37500.0,1.0,2014.0,5k to 10k miles,"[5000, 10000]",...,NaN,E,Red,2.0L,4,41.0,38,181,10.0,13
3,$35k to $40k,"[35000, 40000]",37500.0,$5k to $10k,"[5000, 10000]",7500.0,1.0,2014.0,15k to 20k miles,"[15000, 20000]",...,Premium,F,Blue,3.0L,6,17.0,25,230,16.0,13
4,$30k to $35k,"[30000, 35000]",32500.0,$15k to $20k,"[15000, 20000]",17500.0,1.0,2011.0,35k to 40k miles,"[35000, 40000]",...,Not Premium,E,Black,2.4L,4,20.0,29,182,18.0,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,$15k to $20k,"[15000, 20000]",17500.0,$15k to $20k,"[15000, 20000]",17500.0,1.0,2013.0,10k to 15k miles,"[10000, 15000]",...,Not Premium,E,Black,1.4L,4,26.0,31,138,14.0,1
199996,$20k to $25k,"[20000, 25000]",22500.0,$10k to $15k,"[10000, 15000]",12500.0,0.0,2014.0,55k to 60k miles,"[55000, 60000]",...,Not Premium,B,Black,1.8L,4,30.0,39,143,13.0,8
199997,$30k to $35k,"[30000, 35000]",32500.0,$0k to $5k,"[0, 5000]",2500.0,0.0,2014.0,10k to 15k miles,"[10000, 15000]",...,Not Premium,F,Gray,2.4L,4,21.0,30,177,18.0,3
199998,$30k to $35k,"[30000, 35000]",32500.0,$10k to $15k,"[10000, 15000]",12500.0,0.0,2012.0,50k to 55k miles,"[50000, 55000]",...,Premium,D,White,5.7L,8,13.0,19,390,26.0,11
199999,$50k to $55k,"[50000, 55000]",52500.0,$15k to $20k,"[15000, 20000]",17500.0,0.0,2014.0,5k to 10k miles,"[5000, 10000]",...,Premium,E,Blue,5.7L,8,18.0,25,360,24.0,14

In [124]:
df_og4 = df_full3

In [125]:
data = []
for i in range(len(df_og4)):
    local = df_og4.iloc[i]['mileage_appraisal'].replace('$', '').replace('k', '').replace('+', ' ')
    gen = [int(s) for s in local.split() if s.isdigit()]
    numbers = [i * 1000 for i in gen]
    average = sum(numbers) / len(numbers)
    d = {'mileage_appraisal_list': numbers, 'mileage_appraisal_average' : average}
    data.append(d)
df_add4 = pd.DataFrame(data)
df_full4 = df_og4.join(df_add4)
second_col = df_full4.pop('mileage_appraisal_list')
df_full4.insert(24, 'mileage_appraisal_list', second_col)
third_col = df_full4.pop('mileage_appraisal_average')
df_full4.insert(25, 'mileage_appraisal_average', third_col)
df_full4

,price,price_list,price_average,appraisal_offer,appraisal_offer_list,appraisal_offer_average,online_appraisal_flag,model_year,mileage,mileage_list,...,trim_descrip_appraisal,body_appraisal,color_appraisal,engine_appraisal,cylinders_appraisal,mpg_city_appraisal,mpg_highway_appraisal,horsepower_appraisal,fuel_capacity_appraisal,market
0,$20k to $25k,"[20000, 25000]",22500.0,$0k to $5k,"[0, 5000]",2500.0,1.0,2014.0,15k to 20k miles,"[15000, 20000]",...,NaN,D,Silver,4.0L,6,17.0,21,236,21.0,13
1,$15k to $20k,"[15000, 20000]",17500.0,$0k to $5k,"[0, 5000]",2500.0,0.0,2006.0,100k+ miles,[100000],...,Not Premium,D,Gold,4.2L,6,16.0,21,205,25.0,11
2,$30k to $35k,"[30000, 35000]",32500.0,$35k to $40k,"[35000, 40000]",37500.0,1.0,2014.0,5k to 10k miles,"[5000, 10000]",...,NaN,E,Red,2.0L,4,41.0,38,181,10.0,13
3,$35k to $40k,"[35000, 40000]",37500.0,$5k to $10k,"[5000, 10000]",7500.0,1.0,2014.0,15k to 20k miles,"[15000, 20000]",...,Premium,F,Blue,3.0L,6,17.0,25,230,16.0,13
4,$30k to $35k,"[30000, 35000]",32500.0,$15k to $20k,"[15000, 20000]",17500.0,1.0,2011.0,35k to 40k miles,"[35000, 40000]",...,Not Premium,E,Black,2.4L,4,20.0,29,182,18.0,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,$15k to $20k,"[15000, 20000]",17500.0,$15k to $20k,"[15000, 20000]",17500.0,1.0,2013.0,10k to 15k miles,"[10000, 15000]",...,Not Premium,E,Black,1.4L,4,26.0,31,138,14.0,1
199996,$20k to $25k,"[20000, 25000]",22500.0,$10k to $15k,"[10000, 15000]",12500.0,0.0,2014.0,55k to 60k miles,"[55000, 60000]",...,Not Premium,B,Black,1.8L,4,30.0,39,143,13.0,8
199997,$30k to $35k,"[30000, 35000]",32500.0,$0k to $5k,"[0, 5000]",2500.0,0.0,2014.0,10k to 15k miles,"[10000, 15000]",...,Not Premium,F,Gray,2.4L,4,21.0,30,177,18.0,3
199998,$30k to $35k,"[30000, 35000]",32500.0,$10k to $15k,"[10000, 15000]",12500.0,0.0,2012.0,50k to 55k miles,"[50000, 55000]",...,Premium,D,White,5.7L,8,13.0,19,390,26.0,11
199999,$50k to $55k,"[50000, 55000]",52500.0,$15k to $20k,"[15000, 20000]",17500.0,0.0,2014.0,5k to 10k miles,"[5000, 10000]",...,Premium,E,Blue,5.7L,8,18.0,25,360,24.0,14

In [127]:
df_og5 = df_full4

,price,price_list,price_average,appraisal_offer,appraisal_offer_list,appraisal_offer_average,online_appraisal_flag,model_year,mileage,mileage_list,...,trim_descrip_appraisal,body_appraisal,color_appraisal,engine_appraisal,cylinders_appraisal,mpg_city_appraisal,mpg_highway_appraisal,horsepower_appraisal,fuel_capacity_appraisal,market
0,$20k to $25k,"[20000, 25000]",22500.0,$0k to $5k,"[0, 5000]",2500.0,1.0,2014.0,15k to 20k miles,"[15000, 20000]",...,NaN,D,Silver,4.0L,6,17.0,21,236,21.0,13
1,$15k to $20k,"[15000, 20000]",17500.0,$0k to $5k,"[0, 5000]",2500.0,0.0,2006.0,100k+ miles,[100000],...,Not Premium,D,Gold,4.2L,6,16.0,21,205,25.0,11
2,$30k to $35k,"[30000, 35000]",32500.0,$35k to $40k,"[35000, 40000]",37500.0,1.0,2014.0,5k to 10k miles,"[5000, 10000]",...,NaN,E,Red,2.0L,4,41.0,38,181,10.0,13
3,$35k to $40k,"[35000, 40000]",37500.0,$5k to $10k,"[5000, 10000]",7500.0,1.0,2014.0,15k to 20k miles,"[15000, 20000]",...,Premium,F,Blue,3.0L,6,17.0,25,230,16.0,13
4,$30k to $35k,"[30000, 35000]",32500.0,$15k to $20k,"[15000, 20000]",17500.0,1.0,2011.0,35k to 40k miles,"[35000, 40000]",...,Not Premium,E,Black,2.4L,4,20.0,29,182,18.0,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,$15k to $20k,"[15000, 20000]",17500.0,$15k to $20k,"[15000, 20000]",17500.0,1.0,2013.0,10k to 15k miles,"[10000, 15000]",...,Not Premium,E,Black,1.4L,4,26.0,31,138,14.0,1
199996,$20k to $25k,"[20000, 25000]",22500.0,$10k to $15k,"[10000, 15000]",12500.0,0.0,2014.0,55k to 60k miles,"[55000, 60000]",...,Not Premium,B,Black,1.8L,4,30.0,39,143,13.0,8
199997,$30k to $35k,"[30000, 35000]",32500.0,$0k to $5k,"[0, 5000]",2500.0,0.0,2014.0,10k to 15k miles,"[10000, 15000]",...,Not Premium,F,Gray,2.4L,4,21.0,30,177,18.0,3
199998,$30k to $35k,"[30000, 35000]",32500.0,$10k to $15k,"[10000, 15000]",12500.0,0.0,2012.0,50k to 55k miles,"[50000, 55000]",...,Premium,D,White,5.7L,8,13.0,19,390,26.0,11
199999,$50k to $55k,"[50000, 55000]",52500.0,$15k to $20k,"[15000, 20000]",17500.0,0.0,2014.0,5k to 10k miles,"[5000, 10000]",...,Premium,E,Blue,5.7L,8,18.0,25,360,24.0,14

In [123]:
data = []
for i in range(len(df_samp4)):
    local = df_samp4.iloc[i]['mileage_appraisal'].replace('$', '').replace('k', '').replace('+', ' ')
    gen = [int(s) for s in local.split() if s.isdigit()]
    numbers = [i * 1000 for i in gen]
    average = sum(numbers) / len(numbers)
    d = {'mileage_appraisal_list': numbers, 'mileage_appraisal_average' : average}
    data.append(d)
df_samp_add4 = pd.DataFrame(data)
df_samp_final4 = df_samp4.join(df_samp_add4)
second_col = df_samp_final4.pop('mileage_appraisal_list')
df_samp_final4.insert(24, 'mileage_appraisal_list', second_col)
third_col = df_samp_final4.pop('mileage_appraisal_average')
df_samp_final4.insert(25, 'mileage_appraisal_average', third_col)
df_samp5 = df_samp_final4
df_samp5

,price,price_list,price_average,appraisal_offer,appraisal_offer_list,appraisal_offer_average,online_appraisal_flag,model_year,mileage,mileage_list,...,trim_descrip_appraisal,body_appraisal,color_appraisal,engine_appraisal,cylinders_appraisal,mpg_city_appraisal,mpg_highway_appraisal,horsepower_appraisal,fuel_capacity_appraisal,market
0,$20k to $25k,"[20000, 25000]",22500.0,$0k to $5k,"[0, 5000]",2500.0,1,2014.0,15k to 20k miles,"[15000, 20000]",...,NaN,D,Silver,4.0L,6,17,21,236,21,13
1,$15k to $20k,"[15000, 20000]",17500.0,$0k to $5k,"[0, 5000]",2500.0,0,2006.0,100k+ miles,[100000],...,Not Premium,D,Gold,4.2L,6,16,21,205,25,11
2,$30k to $35k,"[30000, 35000]",32500.0,$35k to $40k,"[35000, 40000]",37500.0,1,2014.0,5k to 10k miles,"[5000, 10000]",...,NaN,E,Red,2.0L,4,41,38,181,10,13
3,$35k to $40k,"[35000, 40000]",37500.0,$5k to $10k,"[5000, 10000]",7500.0,1,2014.0,15k to 20k miles,"[15000, 20000]",...,Premium,F,Blue,3.0L,6,17,25,230,16,13
4,$30k to $35k,"[30000, 35000]",32500.0,$15k to $20k,"[15000, 20000]",17500.0,1,2011.0,35k to 40k miles,"[35000, 40000]",...,Not Premium,E,Black,2.4L,4,20,29,182,18,16
5,$15k to $20k,"[15000, 20000]",17500.0,$5k to $10k,"[5000, 10000]",7500.0,0,2013.0,35k to 40k miles,"[35000, 40000]",...,Not Premium,F,Black,3.6L,6,18,27,292,19,10
6,$35k to $40k,"[35000, 40000]",37500.0,$40k+,[40000],40000.0,0,2013.0,20k to 25k miles,"[20000, 25000]",...,Not Premium,B,Black,6.2L,8,16,25,455,18,8
7,$15k to $20k,"[15000, 20000]",17500.0,$5k to $10k,"[5000, 10000]",7500.0,0,2012.0,30k to 35k miles,"[30000, 35000]",...,Not Premium,F,Silver,1.8L,4,30,39,143,13,1
8,$30k to $35k,"[30000, 35000]",32500.0,$20k to $25k,"[20000, 25000]",22500.0,0,2013.0,35k to 40k miles,"[35000, 40000]",...,Premium,E,Black,3.6L,6,17,24,288,22,9
9,$20k to $25k,"[20000, 25000]",22500.0,$0k to $5k,"[0, 5000]",2500.0,0,2015.0,45k to 50k miles,"[45000, 50000]",...,Not Premium,E,Blue,4.7L,8,15,21,235,20,16
10,$30k to $35k,"[30000, 35000]",32500.0,$5k to $10k,"[5000, 10000]",7500.0,1,2014.0,15k to 20k miles,"[15000, 20000]",...,NaN,F,Silver,3.5L,6,21,30,272,18,11
11,$45k to $50k,"[45000, 50000]",47500.0,$0k to $5k,"[0, 5000]",2500.0,0,2012.0,70k to 75k miles,"[70000, 75000]",...,NaN,E,Burgundy,3.5L,6,16,21,268,21,12

In [133]:
import math

In [143]:

for i in range(len(df_og5)):
    if(math.isnan(df_og5.iloc[i]['online_appraisal_flag'])):
        df_og5.at[i, 'online_appraisal_flag'] = 0
df_og5

,price,price_list,price_average,appraisal_offer,appraisal_offer_list,appraisal_offer_average,online_appraisal_flag,model_year,mileage,mileage_list,...,trim_descrip_appraisal,body_appraisal,color_appraisal,engine_appraisal,cylinders_appraisal,mpg_city_appraisal,mpg_highway_appraisal,horsepower_appraisal,fuel_capacity_appraisal,market
0,$20k to $25k,"[20000, 25000]",22500.0,$0k to $5k,"[0, 5000]",2500.0,1.0,2014.0,15k to 20k miles,"[15000, 20000]",...,NaN,D,Silver,4.0L,6,17.0,21,236,21.0,13
1,$15k to $20k,"[15000, 20000]",17500.0,$0k to $5k,"[0, 5000]",2500.0,0.0,2006.0,100k+ miles,[100000],...,Not Premium,D,Gold,4.2L,6,16.0,21,205,25.0,11
2,$30k to $35k,"[30000, 35000]",32500.0,$35k to $40k,"[35000, 40000]",37500.0,1.0,2014.0,5k to 10k miles,"[5000, 10000]",...,NaN,E,Red,2.0L,4,41.0,38,181,10.0,13
3,$35k to $40k,"[35000, 40000]",37500.0,$5k to $10k,"[5000, 10000]",7500.0,1.0,2014.0,15k to 20k miles,"[15000, 20000]",...,Premium,F,Blue,3.0L,6,17.0,25,230,16.0,13
4,$30k to $35k,"[30000, 35000]",32500.0,$15k to $20k,"[15000, 20000]",17500.0,1.0,2011.0,35k to 40k miles,"[35000, 40000]",...,Not Premium,E,Black,2.4L,4,20.0,29,182,18.0,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,$15k to $20k,"[15000, 20000]",17500.0,$15k to $20k,"[15000, 20000]",17500.0,1.0,2013.0,10k to 15k miles,"[10000, 15000]",...,Not Premium,E,Black,1.4L,4,26.0,31,138,14.0,1
199996,$20k to $25k,"[20000, 25000]",22500.0,$10k to $15k,"[10000, 15000]",12500.0,0.0,2014.0,55k to 60k miles,"[55000, 60000]",...,Not Premium,B,Black,1.8L,4,30.0,39,143,13.0,8
199997,$30k to $35k,"[30000, 35000]",32500.0,$0k to $5k,"[0, 5000]",2500.0,0.0,2014.0,10k to 15k miles,"[10000, 15000]",...,Not Premium,F,Gray,2.4L,4,21.0,30,177,18.0,3
199998,$30k to $35k,"[30000, 35000]",32500.0,$10k to $15k,"[10000, 15000]",12500.0,0.0,2012.0,50k to 55k miles,"[50000, 55000]",...,Premium,D,White,5.7L,8,13.0,19,390,26.0,11
199999,$50k to $55k,"[50000, 55000]",52500.0,$15k to $20k,"[15000, 20000]",17500.0,0.0,2014.0,5k to 10k miles,"[5000, 10000]",...,Premium,E,Blue,5.7L,8,18.0,25,360,24.0,14

In [145]:
df_og5.iloc[7]['online_appraisal_flag']

0.0

In [158]:
sum = 0
for i in range(len(df_og5)):
    if(math.isnan(df_og5.iloc[i]['online_appraisal_flag'])):
        sum+=1
print(sum)

0

In [159]:
sum = 0
for i in range(len(df_og5)):
    if(math.isnan(df_og4.iloc[i]['online_appraisal_flag'])):
        sum+=1
print(sum)

3834

In [160]:
sum = 0
for i in range(len(df_og5)):
    if(pd.isna((df_og5.iloc[i]['trim_descrip']))):
        sum+=1
print(sum)

23841

In [161]:
df_og5

,price,price_list,price_average,appraisal_offer,appraisal_offer_list,appraisal_offer_average,online_appraisal_flag,model_year,mileage,mileage_list,...,trim_descrip_appraisal,body_appraisal,color_appraisal,engine_appraisal,cylinders_appraisal,mpg_city_appraisal,mpg_highway_appraisal,horsepower_appraisal,fuel_capacity_appraisal,market
0,$20k to $25k,"[20000, 25000]",22500.0,$0k to $5k,"[0, 5000]",2500.0,1.0,2014.0,15k to 20k miles,"[15000, 20000]",...,NaN,D,Silver,4.0L,6,17.0,21,236,21.0,13
1,$15k to $20k,"[15000, 20000]",17500.0,$0k to $5k,"[0, 5000]",2500.0,0.0,2006.0,100k+ miles,[100000],...,Not Premium,D,Gold,4.2L,6,16.0,21,205,25.0,11
2,$30k to $35k,"[30000, 35000]",32500.0,$35k to $40k,"[35000, 40000]",37500.0,1.0,2014.0,5k to 10k miles,"[5000, 10000]",...,NaN,E,Red,2.0L,4,41.0,38,181,10.0,13
3,$35k to $40k,"[35000, 40000]",37500.0,$5k to $10k,"[5000, 10000]",7500.0,1.0,2014.0,15k to 20k miles,"[15000, 20000]",...,Premium,F,Blue,3.0L,6,17.0,25,230,16.0,13
4,$30k to $35k,"[30000, 35000]",32500.0,$15k to $20k,"[15000, 20000]",17500.0,1.0,2011.0,35k to 40k miles,"[35000, 40000]",...,Not Premium,E,Black,2.4L,4,20.0,29,182,18.0,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,$15k to $20k,"[15000, 20000]",17500.0,$15k to $20k,"[15000, 20000]",17500.0,1.0,2013.0,10k to 15k miles,"[10000, 15000]",...,Not Premium,E,Black,1.4L,4,26.0,31,138,14.0,1
199996,$20k to $25k,"[20000, 25000]",22500.0,$10k to $15k,"[10000, 15000]",12500.0,0.0,2014.0,55k to 60k miles,"[55000, 60000]",...,Not Premium,B,Black,1.8L,4,30.0,39,143,13.0,8
199997,$30k to $35k,"[30000, 35000]",32500.0,$0k to $5k,"[0, 5000]",2500.0,0.0,2014.0,10k to 15k miles,"[10000, 15000]",...,Not Premium,F,Gray,2.4L,4,21.0,30,177,18.0,3
199998,$30k to $35k,"[30000, 35000]",32500.0,$10k to $15k,"[10000, 15000]",12500.0,0.0,2012.0,50k to 55k miles,"[50000, 55000]",...,Premium,D,White,5.7L,8,13.0,19,390,26.0,11
199999,$50k to $55k,"[50000, 55000]",52500.0,$15k to $20k,"[15000, 20000]",17500.0,0.0,2014.0,5k to 10k miles,"[5000, 10000]",...,Premium,E,Blue,5.7L,8,18.0,25,360,24.0,14

In [163]:
df_og5.to_csv('CarMax_Data_With_Null', index=False)

In [167]:
df_og6 = df_og5

In [165]:
sum = 0
for i in range(len(df_og5)):
    if(math.isnan(df_og5.iloc[i]['mpg_highway'])):
        sum+=1
print(sum)

590

In [169]:
df_og6 = df_og6[(df_og6['mpg_highway'].notna()) & (df_og6['mpg_city'].notna()) & (df_og6['fuel_capacity'].notna()) & (df_og6['mpg_city_appraisal'].notna()) & (df_og6['mpg_highway_appraisal'].notna()) & (df_og6['fuel_capacity_appraisal'].notna())]
len(df_og6)

199093

In [170]:
df_og6.to_csv('CarMax_Data_Without_Null', index=False)